/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2025-03-16 14:51:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("<title>Aroma Shop - Footer</title>\r\n");
      out.write("<link rel=\"icon\" href=\"img/Fevicon.png\" type=\"image/png\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/vendors/bootstrap/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/vendors/fontawesome/css/all.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"assets/vendors/themify-icons/themify-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/vendors/linericon/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"assets/vendors/owl-carousel/owl.theme.default.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"assets/vendors/owl-carousel/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/vendors/nice-select/nice-select.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"assets/vendors/nouislider/nouislider.min.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!--================ Start footer Area  =================-->\r\n");
      out.write("	<div class=\"footer-area footer-only\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row section_gap\">\r\n");
      out.write("				<div class=\"col-lg-3 col-md-6 col-sm-6\">\r\n");
      out.write("					<div class=\"single-footer-widget tp_widgets \">\r\n");
      out.write("						<h4 class=\"footer_title large_title\">Nhiệm vụ</h4>\r\n");
      out.write("						<p>Chúng tôi cam kết mang đến những sản phẩm chất lượng cao,\r\n");
      out.write("							đáp ứng nhu cầu của khách hàng với sự tận tâm và chuyên nghiệp.</p>\r\n");
      out.write("						<p>Luôn đổi mới, sáng tạo và không ngừng phát triển để mang\r\n");
      out.write("							đến trải nghiệm mua sắm tốt nhất.</p>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"offset-lg-1 col-lg-2 col-md-6 col-sm-6\">\r\n");
      out.write("					<div class=\"single-footer-widget tp_widgets\">\r\n");
      out.write("						<h4 class=\"footer_title\">Liên kết</h4>\r\n");
      out.write("						<ul class=\"list\">\r\n");
      out.write("							<li><a href=\"Home.jsp\">Trang chủ</a></li>\r\n");
      out.write("							<li><a href=\"Shop.jsp\">Cửa hàng</a></li>\r\n");
      out.write("							<li><a href=\"Blog.jsp\">Blog</a></li>\r\n");
      out.write("							<li><a href=\"Contact.jsp\">Liên hệ</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-2 col-md-6 col-sm-6\">\r\n");
      out.write("					<div class=\"single-footer-widget instafeed\">\r\n");
      out.write("						<h4 class=\"footer_title\">Phòng trưng bày</h4>\r\n");
      out.write("						<ul class=\"list instafeed d-flex flex-wrap\">\r\n");
      out.write("							<li><img src=\"img/gallery/r1.jpg\" alt=\"\"></li>\r\n");
      out.write("							<li><img src=\"img/gallery/r2.jpg\" alt=\"\"></li>\r\n");
      out.write("							<li><img src=\"img/gallery/r3.jpg\" alt=\"\"></li>\r\n");
      out.write("							<li><img src=\"img/gallery/r5.jpg\" alt=\"\"></li>\r\n");
      out.write("							<li><img src=\"img/gallery/r7.jpg\" alt=\"\"></li>\r\n");
      out.write("							<li><img src=\"img/gallery/r8.jpg\" alt=\"\"></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"offset-lg-1 col-lg-3 col-md-6 col-sm-6\">\r\n");
      out.write("					<div class=\"single-footer-widget tp_widgets\">\r\n");
      out.write("						<h4 class=\"footer_title\">Liện hệ với chúng tôi</h4>\r\n");
      out.write("						<div class=\"ml-40\">\r\n");
      out.write("							<p class=\"sm-head\">\r\n");
      out.write("								<span class=\"fa fa-location-arrow\"></span> Trụ sở chính\r\n");
      out.write("							</p>\r\n");
      out.write("							<p>Khu phố 6, Phường Linh Trung, TP. Thủ Đức, TP. Hồ Chí Minh</p>\r\n");
      out.write("\r\n");
      out.write("							<p class=\"sm-head\">\r\n");
      out.write("								<span class=\"fa fa-phone\"></span> Số điện thoại\r\n");
      out.write("							</p>\r\n");
      out.write("							<p>\r\n");
      out.write("								+84 123 456 789 <br> +84 987 654 321\r\n");
      out.write("							</p>\r\n");
      out.write("\r\n");
      out.write("							<p class=\"sm-head\">\r\n");
      out.write("								<span class=\"fa fa-envelope\"></span> Email\r\n");
      out.write("							</p>\r\n");
      out.write("							<p>\r\n");
      out.write("								atbm@st.hcmuaf.edu.vn <br> www.atbm.com\r\n");
      out.write("							</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"footer-bottom\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row d-flex\">\r\n");
      out.write("				<p class=\"col-lg-12 footer-text text-center\">\r\n");
      out.write("					© 2025 Công Ty XYZ.| \r\n");
      out.write("					<a href=\"PrivacyPolicy.html\" class=\"text-white\">Chính sách bảo mật</a> | \r\n");
      out.write("					<a href=\"TermsOfUse.html\" class=\"text-white\">Điều khoản sử dụng</a> | \r\n");
      out.write("					<a href=\"Contact,jsp\" class=\"text-white\">Liên hệ</a>\r\n");
      out.write("				</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!--================ End footer Area  =================-->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
