/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2025-03-18 15:43:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class productdetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1741227894793L));
    _jspx_dependants.put("jar:file:/D:/ATBMHTTT/An-Toan-Bao-Mat-Thong-Tin-He-Thong/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ATBM/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425953470000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("    <title>Aroma Shop - Product Details</title>\r\n");
      out.write("    <link rel=\"icon\" href=\"assets/img/Fevicon.png\" type=\"image/png\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/vendors/bootstrap/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/vendors/fontawesome/css/all.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/vendors/themify-icons/themify-icons.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/vendors/linericon/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/vendors/owl-carousel/owl.theme.default.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/vendors/owl-carousel/owl.carousel.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/vendors/nice-select/nice-select.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/vendors/nouislider/nouislider.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/style.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("    /* Quantity buttons styling */\r\n");
      out.write(".product_count {\r\n");
      out.write("    margin-bottom: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product_count .d-flex {\r\n");
      out.write("    border: 1px solid #e5e5e5;\r\n");
      out.write("    border-radius: 25px;\r\n");
      out.write("    display: inline-flex !important;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    padding: 0 5px;\r\n");
      out.write("    max-width: 150px;\r\n");
      out.write("    height: 45px;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write(".product_count .reduced {\r\n");
      out.write("   \r\n");
      out.write("    right: 80px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product_count .input-text.qty {\r\n");
      out.write("    width: 50px;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    border: none;\r\n");
      out.write("    background: transparent;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    font-weight: 500;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product_count .items-count {\r\n");
      out.write("    background: transparent;\r\n");
      out.write("    border: none;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    width: 35px;\r\n");
      out.write("    height: 35px;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    transition: all 0.3s ease;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product_count .items-count:hover {\r\n");
      out.write("    background-color: #f8f8f8;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product_count .items-count i {\r\n");
      out.write("    color: #888;\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product_count .items-count:hover i {\r\n");
      out.write("    color: #555;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Add to Cart button styling */\r\n");
      out.write(".button.primary-btn {\r\n");
      out.write("    background: #384aeb;\r\n");
      out.write("    border: none;\r\n");
      out.write("    color: white;\r\n");
      out.write("    border-radius: 30px;\r\n");
      out.write("    padding: 12px 30px;\r\n");
      out.write("    font-weight: 500;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    text-transform: uppercase;\r\n");
      out.write("    letter-spacing: 1px;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    transition: all 0.3s ease;\r\n");
      out.write("    box-shadow: 0 5px 15px rgba(56, 74, 235, 0.2);\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    outline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button.primary-btn::before {\r\n");
      out.write("    content: \"\";\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    left: -100%;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    background: linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.2), transparent);\r\n");
      out.write("    transition: all 0.6s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button.primary-btn:hover {\r\n");
      out.write("    background: #2a3ad0;\r\n");
      out.write("    transform: translateY(-3px);\r\n");
      out.write("    box-shadow: 0 8px 20px rgba(56, 74, 235, 0.3);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button.primary-btn:hover::before {\r\n");
      out.write("    left: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button.primary-btn:active {\r\n");
      out.write("    transform: translateY(-1px);\r\n");
      out.write("    box-shadow: 0 5px 15px rgba(56, 74, 235, 0.2);\r\n");
      out.write("}</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	 ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/header.jsp", out, false);
      out.write("\r\n");
      out.write("	<!-- ================ start banner area ================= -->	\r\n");
      out.write("	<section class=\"blog-banner-area\" id=\"blog\">\r\n");
      out.write("		<div class=\"container h-100\">\r\n");
      out.write("			<div class=\"blog-banner\">\r\n");
      out.write("				<div class=\"text-center\">\r\n");
      out.write("					<h1>Produc Details</h1>\r\n");
      out.write("					<nav aria-label=\"breadcrumb\" class=\"banner-breadcrumb\">\r\n");
      out.write("            <ol class=\"breadcrumb\">\r\n");
      out.write("              <li class=\"breadcrumb-item\"><a href=\"#\">Home</a></li>\r\n");
      out.write("              <li class=\"breadcrumb-item active\" aria-current=\"page\">Shop Single</li>\r\n");
      out.write("            </ol>\r\n");
      out.write("          </nav>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("    </div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- ================ end banner area ================= -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Display success message if it exists -->\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  <!--================Single Product Area =================-->\r\n");
      out.write("    <div class=\"product_image_area\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row s_product_inner\">\r\n");
      out.write("                <div class=\"col-lg-6\">\r\n");
      out.write("                    <div class=\"single-prd-item\">\r\n");
      out.write("                        <img class=\"img-fluid\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-5 offset-lg-1\">\r\n");
      out.write("                    <div class=\"s_product_text\">\r\n");
      out.write("                        <h3>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\r\n");
      out.write("                        <h2>$");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h2>\r\n");
      out.write("                        <ul class=\"list\">\r\n");
      out.write("                            <li><a class=\"active\" href=\"#\"><span>Category</span> : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.categoryId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a></li>\r\n");
      out.write("                            <li><a href=\"#\"><span>Availability</span> : In Stock</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.description}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("                        <div class=\"product_count\">\r\n");
      out.write("                            <form action=\"ProductController\" method=\"post\">\r\n");
      out.write("                                <input type=\"hidden\" name=\"action\" value=\"addToCart\">\r\n");
      out.write("                                <input type=\"hidden\" name=\"productId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.productId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                <div class=\"mb-3\">\r\n");
      out.write("                                    <label for=\"qty\">Quantity:</label>\r\n");
      out.write("                                    <div class=\"d-flex align-items-center\">\r\n");
      out.write("                                        <button type=\"button\" style=\"top:8px;\" class=\"reduced items-count\" onclick=\"decreaseQuantity()\">\r\n");
      out.write("                                            <i class=\"ti-angle-left\"></i>\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                        <input type=\"text\" name=\"qty\" id=\"sst\" size=\"2\" maxlength=\"12\" value=\"1\" title=\"Quantity:\" class=\"input-text qty\">\r\n");
      out.write("                                        <button type=\"button\" style=\"top:8px;\" class=\"increase items-count\" onclick=\"increaseQuantity()\">\r\n");
      out.write("                                            <i class=\"ti-angle-right\"></i>\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <button type=\"submit\" class=\"button primary-btn\">Add to Cart</button>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"card_area d-flex align-items-center\">\r\n");
      out.write("                            <a class=\"icon_btn\" href=\"#\"><i class=\"lnr lnr-diamond\"></i></a>\r\n");
      out.write("                            <a class=\"icon_btn\" href=\"#\"><i class=\"lnr lnr-heart\"></i></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--================End Single Product Area =================-->\r\n");
      out.write("\r\n");
      out.write("	<!--================Product Description Area =================-->\r\n");
      out.write("	<section class=\"product_description_area\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<ul class=\"nav nav-tabs\" id=\"myTab\" role=\"tablist\">\r\n");
      out.write("				<li class=\"nav-item\">\r\n");
      out.write("					<a class=\"nav-link\" id=\"home-tab\" data-toggle=\"tab\" href=\"#home\" role=\"tab\" aria-controls=\"home\" aria-selected=\"true\">Description</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"nav-item\">\r\n");
      out.write("					<a class=\"nav-link\" id=\"profile-tab\" data-toggle=\"tab\" href=\"#profile\" role=\"tab\" aria-controls=\"profile\"\r\n");
      out.write("					 aria-selected=\"false\">Specification</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"nav-item\">\r\n");
      out.write("					<a class=\"nav-link\" id=\"contact-tab\" data-toggle=\"tab\" href=\"#contact\" role=\"tab\" aria-controls=\"contact\"\r\n");
      out.write("					 aria-selected=\"false\">Comments</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"nav-item\">\r\n");
      out.write("					<a class=\"nav-link active\" id=\"review-tab\" data-toggle=\"tab\" href=\"#review\" role=\"tab\" aria-controls=\"review\"\r\n");
      out.write("					 aria-selected=\"false\">Reviews</a>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			<div class=\"tab-content\" id=\"myTabContent\">\r\n");
      out.write("				<div class=\"tab-pane fade\" id=\"home\" role=\"tabpanel\" aria-labelledby=\"home-tab\">\r\n");
      out.write("					<p>Beryl Cook is one of Britain’s most talented and amusing artists .Beryl’s pictures feature women of all shapes\r\n");
      out.write("						and sizes enjoying themselves .Born between the two world wars, Beryl Cook eventually left Kendrick School in\r\n");
      out.write("						Reading at the age of 15, where she went to secretarial school and then into an insurance office. After moving to\r\n");
      out.write("						London and then Hampton, she eventually married her next door neighbour from Reading, John Cook. He was an\r\n");
      out.write("						officer in the Merchant Navy and after he left the sea in 1956, they bought a pub for a year before John took a\r\n");
      out.write("						job in Southern Rhodesia with a motor company. Beryl bought their young son a box of watercolours, and when\r\n");
      out.write("						showing him how to use it, she decided that she herself quite enjoyed painting. John subsequently bought her a\r\n");
      out.write("						child’s painting set for her birthday and it was with this that she produced her first significant work, a\r\n");
      out.write("						half-length portrait of a dark-skinned lady with a vacant expression and large drooping breasts. It was aptly\r\n");
      out.write("						named ‘Hangover’ by Beryl’s husband and</p>\r\n");
      out.write("					<p>It is often frustrating to attempt to plan meals that are designed for one. Despite this fact, we are seeing\r\n");
      out.write("						more and more recipe books and Internet websites that are dedicated to the act of cooking for one. Divorce and\r\n");
      out.write("						the death of spouses or grown children leaving for college are all reasons that someone accustomed to cooking for\r\n");
      out.write("						more than one would suddenly need to learn how to adjust all the cooking practices utilized before into a\r\n");
      out.write("						streamlined plan of cooking that is more efficient for one person creating less</p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"tab-pane fade\" id=\"profile\" role=\"tabpanel\" aria-labelledby=\"profile-tab\">\r\n");
      out.write("					<div class=\"table-responsive\">\r\n");
      out.write("						<table class=\"table\">\r\n");
      out.write("							<tbody>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>Width</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>128mm</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>Height</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>508mm</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>Depth</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>85mm</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>Weight</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>52gm</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>Quality checking</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>yes</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>Freshness Duration</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>03days</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>When packeting</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>Without touch of hand</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>Each Box contains</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>60pcs</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("							</tbody>\r\n");
      out.write("						</table>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"tab-pane fade\" id=\"contact\" role=\"tabpanel\" aria-labelledby=\"contact-tab\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-lg-6\">\r\n");
      out.write("							<div class=\"comment_list\">\r\n");
      out.write("								<div class=\"review_item\">\r\n");
      out.write("									<div class=\"media\">\r\n");
      out.write("										<div class=\"d-flex\">\r\n");
      out.write("											<img src=\"img/product/review-1.png\" alt=\"\">\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"media-body\">\r\n");
      out.write("											<h4>Blake Ruiz</h4>\r\n");
      out.write("											<h5>12th Feb, 2018 at 05:56 pm</h5>\r\n");
      out.write("											<a class=\"reply_btn\" href=\"#\">Reply</a>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et\r\n");
      out.write("										dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea\r\n");
      out.write("										commodo</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"review_item reply\">\r\n");
      out.write("									<div class=\"media\">\r\n");
      out.write("										<div class=\"d-flex\">\r\n");
      out.write("											<img src=\"img/product/review-2.png\" alt=\"\">\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"media-body\">\r\n");
      out.write("											<h4>Blake Ruiz</h4>\r\n");
      out.write("											<h5>12th Feb, 2018 at 05:56 pm</h5>\r\n");
      out.write("											<a class=\"reply_btn\" href=\"#\">Reply</a>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et\r\n");
      out.write("										dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea\r\n");
      out.write("										commodo</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"review_item\">\r\n");
      out.write("									<div class=\"media\">\r\n");
      out.write("										<div class=\"d-flex\">\r\n");
      out.write("											<img src=\"img/product/review-3.png\" alt=\"\">\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"media-body\">\r\n");
      out.write("											<h4>Blake Ruiz</h4>\r\n");
      out.write("											<h5>12th Feb, 2018 at 05:56 pm</h5>\r\n");
      out.write("											<a class=\"reply_btn\" href=\"#\">Reply</a>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et\r\n");
      out.write("										dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea\r\n");
      out.write("										commodo</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-lg-6\">\r\n");
      out.write("							<div class=\"review_box\">\r\n");
      out.write("								<h4>Post a comment</h4>\r\n");
      out.write("								<form class=\"row contact_form\" action=\"contact_process.php\" method=\"post\" id=\"contactForm\" novalidate=\"novalidate\">\r\n");
      out.write("									<div class=\"col-md-12\">\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<input type=\"text\" class=\"form-control\" id=\"name\" name=\"name\" placeholder=\"Your Full name\">\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"col-md-12\">\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<input type=\"email\" class=\"form-control\" id=\"email\" name=\"email\" placeholder=\"Email Address\">\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"col-md-12\">\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<input type=\"text\" class=\"form-control\" id=\"number\" name=\"number\" placeholder=\"Phone Number\">\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"col-md-12\">\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<textarea class=\"form-control\" name=\"message\" id=\"message\" rows=\"1\" placeholder=\"Message\"></textarea>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"col-md-12 text-right\">\r\n");
      out.write("										<button type=\"submit\" value=\"submit\" class=\"btn primary-btn\">Submit Now</button>\r\n");
      out.write("									</div>\r\n");
      out.write("								</form>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"tab-pane fade show active\" id=\"review\" role=\"tabpanel\" aria-labelledby=\"review-tab\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-lg-6\">\r\n");
      out.write("							<div class=\"row total_rate\">\r\n");
      out.write("								<div class=\"col-6\">\r\n");
      out.write("									<div class=\"box_total\">\r\n");
      out.write("										<h5>Overall</h5>\r\n");
      out.write("										<h4>4.0</h4>\r\n");
      out.write("										<h6>(03 Reviews)</h6>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"col-6\">\r\n");
      out.write("									<div class=\"rating_list\">\r\n");
      out.write("										<h3>Based on 3 Reviews</h3>\r\n");
      out.write("										<ul class=\"list\">\r\n");
      out.write("											<li><a href=\"#\">5 Star <i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i\r\n");
      out.write("													 class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i> 01</a></li>\r\n");
      out.write("											<li><a href=\"#\">4 Star <i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i\r\n");
      out.write("													 class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i> 01</a></li>\r\n");
      out.write("											<li><a href=\"#\">3 Star <i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i\r\n");
      out.write("													 class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i> 01</a></li>\r\n");
      out.write("											<li><a href=\"#\">2 Star <i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i\r\n");
      out.write("													 class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i> 01</a></li>\r\n");
      out.write("											<li><a href=\"#\">1 Star <i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i\r\n");
      out.write("													 class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i> 01</a></li>\r\n");
      out.write("										</ul>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"review_list\">\r\n");
      out.write("								<div class=\"review_item\">\r\n");
      out.write("									<div class=\"media\">\r\n");
      out.write("										<div class=\"d-flex\">\r\n");
      out.write("											<img src=\"img/product/review-1.png\" alt=\"\">\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"media-body\">\r\n");
      out.write("											<h4>Blake Ruiz</h4>\r\n");
      out.write("											<i class=\"fa fa-star\"></i>\r\n");
      out.write("											<i class=\"fa fa-star\"></i>\r\n");
      out.write("											<i class=\"fa fa-star\"></i>\r\n");
      out.write("											<i class=\"fa fa-star\"></i>\r\n");
      out.write("											<i class=\"fa fa-star\"></i>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et\r\n");
      out.write("										dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea\r\n");
      out.write("										commodo</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"review_item\">\r\n");
      out.write("									<div class=\"media\">\r\n");
      out.write("										<div class=\"d-flex\">\r\n");
      out.write("											<img src=\"img/product/review-2.png\" alt=\"\">\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"media-body\">\r\n");
      out.write("											<h4>Blake Ruiz</h4>\r\n");
      out.write("											<i class=\"fa fa-star\"></i>\r\n");
      out.write("											<i class=\"fa fa-star\"></i>\r\n");
      out.write("											<i class=\"fa fa-star\"></i>\r\n");
      out.write("											<i class=\"fa fa-star\"></i>\r\n");
      out.write("											<i class=\"fa fa-star\"></i>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et\r\n");
      out.write("										dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea\r\n");
      out.write("										commodo</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"review_item\">\r\n");
      out.write("									<div class=\"media\">\r\n");
      out.write("										<div class=\"d-flex\">\r\n");
      out.write("											<img src=\"img/product/review-3.png\" alt=\"\">\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"media-body\">\r\n");
      out.write("											<h4>Blake Ruiz</h4>\r\n");
      out.write("											<i class=\"fa fa-star\"></i>\r\n");
      out.write("											<i class=\"fa fa-star\"></i>\r\n");
      out.write("											<i class=\"fa fa-star\"></i>\r\n");
      out.write("											<i class=\"fa fa-star\"></i>\r\n");
      out.write("											<i class=\"fa fa-star\"></i>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et\r\n");
      out.write("										dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea\r\n");
      out.write("										commodo</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-lg-6\">\r\n");
      out.write("							<div class=\"review_box\">\r\n");
      out.write("								<h4>Add a Review</h4>\r\n");
      out.write("								<p>Your Rating:</p>\r\n");
      out.write("								<ul class=\"list\">\r\n");
      out.write("									<li><a href=\"#\"><i class=\"fa fa-star\"></i></a></li>\r\n");
      out.write("									<li><a href=\"#\"><i class=\"fa fa-star\"></i></a></li>\r\n");
      out.write("									<li><a href=\"#\"><i class=\"fa fa-star\"></i></a></li>\r\n");
      out.write("									<li><a href=\"#\"><i class=\"fa fa-star\"></i></a></li>\r\n");
      out.write("									<li><a href=\"#\"><i class=\"fa fa-star\"></i></a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("								<p>Outstanding</p>\r\n");
      out.write("                <form action=\"#/\" class=\"form-contact form-review mt-3\">\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <input class=\"form-control\" name=\"name\" type=\"text\" placeholder=\"Enter your name\" required>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <input class=\"form-control\" name=\"email\" type=\"email\" placeholder=\"Enter email address\" required>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <input class=\"form-control\" name=\"subject\" type=\"text\" placeholder=\"Enter Subject\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <textarea class=\"form-control different-control w-100\" name=\"textarea\" id=\"textarea\" cols=\"30\" rows=\"5\" placeholder=\"Enter Message\"></textarea>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-group text-center text-md-right mt-3\">\r\n");
      out.write("                    <button type=\"submit\" class=\"button button--active button-review\">Submit Now</button>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </form>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!--================End Product Description Area =================-->\r\n");
      out.write("\r\n");
      out.write("	<!--================ Start related Product area =================-->  \r\n");
      out.write("	<section class=\"related-product-area section-margin--small mt-0\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"section-intro pb-60px\">\r\n");
      out.write("        <p>Popular Item in the market</p>\r\n");
      out.write("        <h2>Top <span class=\"section-intro__style\">Product</span></h2>\r\n");
      out.write("      </div>\r\n");
      out.write("			<div class=\"row mt-30\">\r\n");
      out.write("        <div class=\"col-sm-6 col-xl-3 mb-4 mb-xl-0\">\r\n");
      out.write("          <div class=\"single-search-product-wrapper\">\r\n");
      out.write("            <div class=\"single-search-product d-flex\">\r\n");
      out.write("              <a href=\"#\"><img src=\"img/product/product-sm-1.png\" alt=\"\"></a>\r\n");
      out.write("              <div class=\"desc\">\r\n");
      out.write("                  <a href=\"#\" class=\"title\">Gray Coffee Cup</a>\r\n");
      out.write("                  <div class=\"price\">$170.00</div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"single-search-product d-flex\">\r\n");
      out.write("              <a href=\"#\"><img src=\"img/product/product-sm-2.png\" alt=\"\"></a>\r\n");
      out.write("              <div class=\"desc\">\r\n");
      out.write("                <a href=\"#\" class=\"title\">Gray Coffee Cup</a>\r\n");
      out.write("                <div class=\"price\">$170.00</div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"single-search-product d-flex\">\r\n");
      out.write("              <a href=\"#\"><img src=\"img/product/product-sm-3.png\" alt=\"\"></a>\r\n");
      out.write("              <div class=\"desc\">\r\n");
      out.write("                <a href=\"#\" class=\"title\">Gray Coffee Cup</a>\r\n");
      out.write("                <div class=\"price\">$170.00</div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-sm-6 col-xl-3 mb-4 mb-xl-0\">\r\n");
      out.write("          <div class=\"single-search-product-wrapper\">\r\n");
      out.write("            <div class=\"single-search-product d-flex\">\r\n");
      out.write("              <a href=\"#\"><img src=\"img/product/product-sm-4.png\" alt=\"\"></a>\r\n");
      out.write("              <div class=\"desc\">\r\n");
      out.write("                  <a href=\"#\" class=\"title\">Gray Coffee Cup</a>\r\n");
      out.write("                  <div class=\"price\">$170.00</div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"single-search-product d-flex\">\r\n");
      out.write("              <a href=\"#\"><img src=\"img/product/product-sm-5.png\" alt=\"\"></a>\r\n");
      out.write("              <div class=\"desc\">\r\n");
      out.write("                <a href=\"#\" class=\"title\">Gray Coffee Cup</a>\r\n");
      out.write("                <div class=\"price\">$170.00</div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"single-search-product d-flex\">\r\n");
      out.write("              <a href=\"#\"><img src=\"img/product/product-sm-6.png\" alt=\"\"></a>\r\n");
      out.write("              <div class=\"desc\">\r\n");
      out.write("                <a href=\"#\" class=\"title\">Gray Coffee Cup</a>\r\n");
      out.write("                <div class=\"price\">$170.00</div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-sm-6 col-xl-3 mb-4 mb-xl-0\">\r\n");
      out.write("          <div class=\"single-search-product-wrapper\">\r\n");
      out.write("            <div class=\"single-search-product d-flex\">\r\n");
      out.write("              <a href=\"#\"><img src=\"img/product/product-sm-7.png\" alt=\"\"></a>\r\n");
      out.write("              <div class=\"desc\">\r\n");
      out.write("                  <a href=\"#\" class=\"title\">Gray Coffee Cup</a>\r\n");
      out.write("                  <div class=\"price\">$170.00</div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"single-search-product d-flex\">\r\n");
      out.write("              <a href=\"#\"><img src=\"img/product/product-sm-8.png\" alt=\"\"></a>\r\n");
      out.write("              <div class=\"desc\">\r\n");
      out.write("                <a href=\"#\" class=\"title\">Gray Coffee Cup</a>\r\n");
      out.write("                <div class=\"price\">$170.00</div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"single-search-product d-flex\">\r\n");
      out.write("              <a href=\"#\"><img src=\"img/product/product-sm-9.png\" alt=\"\"></a>\r\n");
      out.write("              <div class=\"desc\">\r\n");
      out.write("                <a href=\"#\" class=\"title\">Gray Coffee Cup</a>\r\n");
      out.write("                <div class=\"price\">$170.00</div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-sm-6 col-xl-3 mb-4 mb-xl-0\">\r\n");
      out.write("          <div class=\"single-search-product-wrapper\">\r\n");
      out.write("            <div class=\"single-search-product d-flex\">\r\n");
      out.write("              <a href=\"#\"><img src=\"img/product/product-sm-1.png\" alt=\"\"></a>\r\n");
      out.write("              <div class=\"desc\">\r\n");
      out.write("                  <a href=\"#\" class=\"title\">Gray Coffee Cup</a>\r\n");
      out.write("                  <div class=\"price\">$170.00</div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"single-search-product d-flex\">\r\n");
      out.write("              <a href=\"#\"><img src=\"img/product/product-sm-2.png\" alt=\"\"></a>\r\n");
      out.write("              <div class=\"desc\">\r\n");
      out.write("                <a href=\"#\" class=\"title\">Gray Coffee Cup</a>\r\n");
      out.write("                <div class=\"price\">$170.00</div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"single-search-product d-flex\">\r\n");
      out.write("              <a href=\"#\"><img src=\"img/product/product-sm-3.png\" alt=\"\"></a>\r\n");
      out.write("              <div class=\"desc\">\r\n");
      out.write("                <a href=\"#\" class=\"title\">Gray Coffee Cup</a>\r\n");
      out.write("                <div class=\"price\">$170.00</div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!--================ end related Product area =================-->  	\r\n");
      out.write("\r\n");
      out.write(" ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/footer.jsp", out, false);
      out.write("\r\n");
      out.write("  <script src=\"assets/vendors/jquery/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendors/bootstrap/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendors/skrollr.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendors/owl-carousel/owl.carousel.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendors/nice-select/jquery.nice-select.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendors/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendors/mail-script.js\"></script>\r\n");
      out.write("  <script src=\"assets/js/main.js\"></script>\r\n");
      out.write("  <script>\r\n");
      out.write("        function increaseQuantity() {\r\n");
      out.write("            var result = document.getElementById('sst');\r\n");
      out.write("            var sst = result.value;\r\n");
      out.write("            if (!isNaN(sst)) result.value++;\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function decreaseQuantity() {\r\n");
      out.write("            var result = document.getElementById('sst');\r\n");
      out.write("            var sst = result.value;\r\n");
      out.write("            if (!isNaN(sst) && sst > 1) result.value--;\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /productdetails.jsp(146,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty sessionScope.message}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("        <div class=\"container mt-3\">\r\n");
          out.write("            <div class=\"alert alert-success\" role=\"alert\">\r\n");
          out.write("                ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("            </div>\r\n");
          out.write("            ");
          if (_jspx_meth_c_005fremove_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("        </div>\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fremove_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:remove
    org.apache.taglibs.standard.tag.common.core.RemoveTag _jspx_th_c_005fremove_005f0 = (org.apache.taglibs.standard.tag.common.core.RemoveTag) _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.common.core.RemoveTag.class);
    boolean _jspx_th_c_005fremove_005f0_reused = false;
    try {
      _jspx_th_c_005fremove_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fremove_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /productdetails.jsp(151,12) name = var type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fremove_005f0.setVar("message");
      // /productdetails.jsp(151,12) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fremove_005f0.setScope("session");
      int _jspx_eval_c_005fremove_005f0 = _jspx_th_c_005fremove_005f0.doStartTag();
      if (_jspx_th_c_005fremove_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.reuse(_jspx_th_c_005fremove_005f0);
      _jspx_th_c_005fremove_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fremove_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fremove_005f0_reused);
    }
    return false;
  }
}
