/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2025-03-18 15:13:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class shop_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1741227894793L));
    _jspx_dependants.put("jar:file:/D:/ATBMHTTT/An-Toan-Bao-Mat-Thong-Tin-He-Thong/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ATBM/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425953470000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("<title>Aroma Shop - Shop</title>\r\n");
      out.write("<link rel=\"icon\" href=\"assets/img/Fevicon.png\" type=\"image/png\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/vendors/bootstrap/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/vendors/fontawesome/css/all.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"assets/vendors/themify-icons/themify-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/vendors/linericon/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"assets/vendors/owl-carousel/owl.theme.default.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"assets/vendors/owl-carousel/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/vendors/nice-select/nice-select.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"assets/vendors/nouislider/nouislider.min.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- ================ start banner area ================= -->\r\n");
      out.write("	<section class=\"blog-banner-area\" id=\"category\">\r\n");
      out.write("		<div class=\"container h-100\">\r\n");
      out.write("			<div class=\"blog-banner\">\r\n");
      out.write("				<div class=\"text-center\">\r\n");
      out.write("					<h1>Shop Category</h1>\r\n");
      out.write("					<nav aria-label=\"breadcrumb\" class=\"banner-breadcrumb\">\r\n");
      out.write("						<ol class=\"breadcrumb\">\r\n");
      out.write("							<li class=\"breadcrumb-item\"><a href=\"#\">Home</a></li>\r\n");
      out.write("							<li class=\"breadcrumb-item active\" aria-current=\"page\">Shop\r\n");
      out.write("								Category</li>\r\n");
      out.write("						</ol>\r\n");
      out.write("					</nav>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- ================ end banner area ================= -->\r\n");
      out.write("	<!-- ================ category section start ================= -->\r\n");
      out.write("	<section class=\"section-margin--small mb-5\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-xl-3 col-lg-4 col-md-5\">\r\n");
      out.write("					<div class=\"sidebar-categories\">\r\n");
      out.write("						<div class=\"head\">Browse Categories</div>\r\n");
      out.write("						<ul class=\"main-categories\">\r\n");
      out.write("							<li class=\"common-filter\">\r\n");
      out.write("								<form action=\"#\">\r\n");
      out.write("									<ul>\r\n");
      out.write("										<li class=\"filter-list\"><input class=\"pixel-radio\"\r\n");
      out.write("											type=\"radio\" id=\"men\" name=\"brand\"><label for=\"men\">Men<span>\r\n");
      out.write("													(3600)</span></label></li>\r\n");
      out.write("										<li class=\"filter-list\"><input class=\"pixel-radio\"\r\n");
      out.write("											type=\"radio\" id=\"women\" name=\"brand\"><label\r\n");
      out.write("											for=\"women\">Women<span> (3600)</span></label></li>\r\n");
      out.write("										<li class=\"filter-list\"><input class=\"pixel-radio\"\r\n");
      out.write("											type=\"radio\" id=\"accessories\" name=\"brand\"><label\r\n");
      out.write("											for=\"accessories\">Accessories<span> (3600)</span></label></li>\r\n");
      out.write("										<li class=\"filter-list\"><input class=\"pixel-radio\"\r\n");
      out.write("											type=\"radio\" id=\"footwear\" name=\"brand\"><label\r\n");
      out.write("											for=\"footwear\">Footwear<span> (3600)</span></label></li>\r\n");
      out.write("										<li class=\"filter-list\"><input class=\"pixel-radio\"\r\n");
      out.write("											type=\"radio\" id=\"bayItem\" name=\"brand\"><label\r\n");
      out.write("											for=\"bayItem\">Bay item<span> (3600)</span></label></li>\r\n");
      out.write("										<li class=\"filter-list\"><input class=\"pixel-radio\"\r\n");
      out.write("											type=\"radio\" id=\"electronics\" name=\"brand\"><label\r\n");
      out.write("											for=\"electronics\">Electronics<span> (3600)</span></label></li>\r\n");
      out.write("										<li class=\"filter-list\"><input class=\"pixel-radio\"\r\n");
      out.write("											type=\"radio\" id=\"food\" name=\"brand\"><label for=\"food\">Food<span>\r\n");
      out.write("													(3600)</span></label></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</form>\r\n");
      out.write("							</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"sidebar-filter\">\r\n");
      out.write("						<div class=\"top-filter-head\">Product Filters</div>\r\n");
      out.write("						<div class=\"common-filter\">\r\n");
      out.write("							<div class=\"head\">Brands</div>\r\n");
      out.write("							<form action=\"#\">\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li class=\"filter-list\"><input class=\"pixel-radio\"\r\n");
      out.write("										type=\"radio\" id=\"apple\" name=\"brand\"><label\r\n");
      out.write("										for=\"apple\">Apple<span>(29)</span></label></li>\r\n");
      out.write("									<li class=\"filter-list\"><input class=\"pixel-radio\"\r\n");
      out.write("										type=\"radio\" id=\"asus\" name=\"brand\"><label for=\"asus\">Asus<span>(29)</span></label></li>\r\n");
      out.write("									<li class=\"filter-list\"><input class=\"pixel-radio\"\r\n");
      out.write("										type=\"radio\" id=\"gionee\" name=\"brand\"><label\r\n");
      out.write("										for=\"gionee\">Gionee<span>(19)</span></label></li>\r\n");
      out.write("									<li class=\"filter-list\"><input class=\"pixel-radio\"\r\n");
      out.write("										type=\"radio\" id=\"micromax\" name=\"brand\"><label\r\n");
      out.write("										for=\"micromax\">Micromax<span>(19)</span></label></li>\r\n");
      out.write("									<li class=\"filter-list\"><input class=\"pixel-radio\"\r\n");
      out.write("										type=\"radio\" id=\"samsung\" name=\"brand\"><label\r\n");
      out.write("										for=\"samsung\">Samsung<span>(19)</span></label></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</form>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"common-filter\">\r\n");
      out.write("							<div class=\"head\">Color</div>\r\n");
      out.write("							<form action=\"#\">\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li class=\"filter-list\"><input class=\"pixel-radio\"\r\n");
      out.write("										type=\"radio\" id=\"black\" name=\"color\"><label\r\n");
      out.write("										for=\"black\">Black<span>(29)</span></label></li>\r\n");
      out.write("									<li class=\"filter-list\"><input class=\"pixel-radio\"\r\n");
      out.write("										type=\"radio\" id=\"balckleather\" name=\"color\"><label\r\n");
      out.write("										for=\"balckleather\">Black Leather<span>(29)</span></label></li>\r\n");
      out.write("									<li class=\"filter-list\"><input class=\"pixel-radio\"\r\n");
      out.write("										type=\"radio\" id=\"blackred\" name=\"color\"><label\r\n");
      out.write("										for=\"blackred\">Black with red<span>(19)</span></label></li>\r\n");
      out.write("									<li class=\"filter-list\"><input class=\"pixel-radio\"\r\n");
      out.write("										type=\"radio\" id=\"gold\" name=\"color\"><label for=\"gold\">Gold<span>(19)</span></label></li>\r\n");
      out.write("									<li class=\"filter-list\"><input class=\"pixel-radio\"\r\n");
      out.write("										type=\"radio\" id=\"spacegrey\" name=\"color\"><label\r\n");
      out.write("										for=\"spacegrey\">Spacegrey<span>(19)</span></label></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</form>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"common-filter\">\r\n");
      out.write("							<div class=\"head\">Price</div>\r\n");
      out.write("							<div class=\"price-range-area\">\r\n");
      out.write("								<div id=\"price-range\"></div>\r\n");
      out.write("								<div class=\"value-wrapper d-flex\">\r\n");
      out.write("									<div class=\"price\">Price:</div>\r\n");
      out.write("									<span>$</span>\r\n");
      out.write("									<div id=\"lower-value\"></div>\r\n");
      out.write("									<div class=\"to\">to</div>\r\n");
      out.write("									<span>$</span>\r\n");
      out.write("									<div id=\"upper-value\"></div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-xl-9 col-lg-8 col-md-7\">\r\n");
      out.write("					<!-- Start Filter Bar -->\r\n");
      out.write("					<div class=\"filter-bar d-flex flex-wrap align-items-center\">\r\n");
      out.write("						<div class=\"sorting\">\r\n");
      out.write("							<select>\r\n");
      out.write("								<option value=\"1\">Default sorting</option>\r\n");
      out.write("								<option value=\"1\">Default sorting</option>\r\n");
      out.write("								<option value=\"1\">Default sorting</option>\r\n");
      out.write("							</select>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"sorting mr-auto\">\r\n");
      out.write("							<select>\r\n");
      out.write("								<option value=\"1\">Show 12</option>\r\n");
      out.write("								<option value=\"1\">Show 12</option>\r\n");
      out.write("								<option value=\"1\">Show 12</option>\r\n");
      out.write("							</select>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<div class=\"input-group filter-bar-search\">\r\n");
      out.write("								<input type=\"text\" placeholder=\"Search\">\r\n");
      out.write("								<div class=\"input-group-append\">\r\n");
      out.write("									<button type=\"button\">\r\n");
      out.write("										<i class=\"ti-search\"></i>\r\n");
      out.write("									</button>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- End Filter Bar -->\r\n");
      out.write("					");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					<!-- Start Best Seller -->\r\n");
      out.write("					<section class=\"lattest-product-area pb-40 category-list\">\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</section>\r\n");
      out.write("					<!-- End Best Seller -->\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- ================ category section end ================= -->\r\n");
      out.write("\r\n");
      out.write("	<!-- ================ top product area start ================= -->\r\n");
      out.write("	<section class=\"related-product-area\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"section-intro pb-60px\">\r\n");
      out.write("				<p>Popular Item in the market</p>\r\n");
      out.write("				<h2>\r\n");
      out.write("					Top <span class=\"section-intro__style\">Product</span>\r\n");
      out.write("				</h2>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row mt-30\">\r\n");
      out.write("				<div class=\"col-sm-6 col-xl-3 mb-4 mb-xl-0\">\r\n");
      out.write("					<div class=\"single-search-product-wrapper\">\r\n");
      out.write("						<div class=\"single-search-product d-flex\">\r\n");
      out.write("							<a href=\"#\"><img src=\"img/product/product-sm-1.png\" alt=\"\"></a>\r\n");
      out.write("							<div class=\"desc\">\r\n");
      out.write("								<a href=\"#\" class=\"title\">Gray Coffee Cup</a>\r\n");
      out.write("								<div class=\"price\">$170.00</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"single-search-product d-flex\">\r\n");
      out.write("							<a href=\"#\"><img src=\"img/product/product-sm-2.png\" alt=\"\"></a>\r\n");
      out.write("							<div class=\"desc\">\r\n");
      out.write("								<a href=\"#\" class=\"title\">Gray Coffee Cup</a>\r\n");
      out.write("								<div class=\"price\">$170.00</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"single-search-product d-flex\">\r\n");
      out.write("							<a href=\"#\"><img src=\"img/product/product-sm-3.png\" alt=\"\"></a>\r\n");
      out.write("							<div class=\"desc\">\r\n");
      out.write("								<a href=\"#\" class=\"title\">Gray Coffee Cup</a>\r\n");
      out.write("								<div class=\"price\">$170.00</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- ================ top product area end ================= -->\r\n");
      out.write("\r\n");
      out.write("	<!-- ================ Subscribe section start ================= -->\r\n");
      out.write("	<section class=\"subscribe-position\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"subscribe text-center\">\r\n");
      out.write("				<h3 class=\"subscribe__title\">Get Update From Anywhere</h3>\r\n");
      out.write("				<p>Bearing Void gathering light light his eavening unto dont\r\n");
      out.write("					afraid</p>\r\n");
      out.write("				<div id=\"mc_embed_signup\">\r\n");
      out.write("					<form target=\"_blank\"\r\n");
      out.write("						action=\"https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01\"\r\n");
      out.write("						method=\"get\" class=\"subscribe-form form-inline mt-5 pt-1\">\r\n");
      out.write("						<div class=\"form-group ml-sm-auto\">\r\n");
      out.write("							<input class=\"form-control mb-1\" type=\"email\" name=\"EMAIL\"\r\n");
      out.write("								placeholder=\"Enter your email\" onfocus=\"this.placeholder = ''\"\r\n");
      out.write("								onblur=\"this.placeholder = 'Your Email Address '\">\r\n");
      out.write("							<div class=\"info\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<button class=\"button button-subscribe mr-auto mb-1\" type=\"submit\">Subscribe\r\n");
      out.write("							Now</button>\r\n");
      out.write("						<div style=\"position: absolute; left: -5000px;\">\r\n");
      out.write("							<input name=\"b_36c4fd991d266f23781ded980_aefe40901a\"\r\n");
      out.write("								tabindex=\"-1\" value=\"\" type=\"text\">\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- ================ Subscribe section end ================= -->\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script src=\"assets/vendors/jquery/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("	<script src=\"assets/vendors/bootstrap/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<script src=\"assets/vendors/skrollr.min.js\"></script>\r\n");
      out.write("	<script src=\"assets/vendors/owl-carousel/owl.carousel.min.js\"></script>\r\n");
      out.write("	<script src=\"assets/vendors/nice-select/jquery.nice-select.min.js\"></script>\r\n");
      out.write("	<script src=\"assets/vendors/nouislider/nouislider.min.js\"></script>\r\n");
      out.write("	<script src=\"assets/vendors/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("	<script src=\"assets/vendors/mail-script.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /shop.jsp(4,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sessionScope.products}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write('\r');
          out.write('\n');
          out.write('	');
          if (_jspx_meth_c_005fredirect_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write('\r');
          out.write('\n');
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fredirect_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:redirect
    org.apache.taglibs.standard.tag.rt.core.RedirectTag _jspx_th_c_005fredirect_005f0 = (org.apache.taglibs.standard.tag.rt.core.RedirectTag) _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.RedirectTag.class);
    boolean _jspx_th_c_005fredirect_005f0_reused = false;
    try {
      _jspx_th_c_005fredirect_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fredirect_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /shop.jsp(5,1) name = url type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fredirect_005f0.setUrl("ProductController?action=shop");
      int _jspx_eval_c_005fredirect_005f0 = _jspx_th_c_005fredirect_005f0.doStartTag();
      if (_jspx_th_c_005fredirect_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.reuse(_jspx_th_c_005fredirect_005f0);
      _jspx_th_c_005fredirect_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fredirect_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fredirect_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /shop.jsp(179,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty sessionScope.message}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("						<div class=\"alert alert-success\" role=\"alert\">\r\n");
          out.write("							");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</div>\r\n");
          out.write("						");
          if (_jspx_meth_c_005fremove_005f0(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fremove_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:remove
    org.apache.taglibs.standard.tag.common.core.RemoveTag _jspx_th_c_005fremove_005f0 = (org.apache.taglibs.standard.tag.common.core.RemoveTag) _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.common.core.RemoveTag.class);
    boolean _jspx_th_c_005fremove_005f0_reused = false;
    try {
      _jspx_th_c_005fremove_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fremove_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /shop.jsp(182,6) name = var type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fremove_005f0.setVar("message");
      // /shop.jsp(182,6) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fremove_005f0.setScope("session");
      int _jspx_eval_c_005fremove_005f0 = _jspx_th_c_005fremove_005f0.doStartTag();
      if (_jspx_th_c_005fremove_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.reuse(_jspx_th_c_005fremove_005f0);
      _jspx_th_c_005fremove_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fremove_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fremove_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /shop.jsp(187,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("product");
      // /shop.jsp(187,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/shop.jsp(187,7) '${products}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${products}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("								<div class=\"col-md-6 col-lg-4\">\r\n");
            out.write("									<div class=\"card text-center card-product\">\r\n");
            out.write("										<div class=\"card-product__img\">\r\n");
            out.write("											<img class=\"card-img\" src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("												alt=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("											<ul class=\"card-product__imgOverlay\">\r\n");
            out.write("												<li><button>\r\n");
            out.write("														<i class=\"ti-search\"></i>\r\n");
            out.write("													</button></li>\r\n");
            out.write("												<li>\r\n");
            out.write("													<form action=\"ProductController\" method=\"post\">\r\n");
            out.write("														<input type=\"hidden\" name=\"action\" value=\"addToCart\">\r\n");
            out.write("														<input type=\"hidden\" name=\"productId\"\r\n");
            out.write("															value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.productId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("														<button type=\"submit\">\r\n");
            out.write("															<i class=\"ti-shopping-cart\"></i>\r\n");
            out.write("														</button>\r\n");
            out.write("													</form>\r\n");
            out.write("												</li>\r\n");
            out.write("\r\n");
            out.write("												<li><button>\r\n");
            out.write("														<i class=\"ti-heart\"></i>\r\n");
            out.write("													</button></li>\r\n");
            out.write("											</ul>\r\n");
            out.write("										</div>\r\n");
            out.write("										<div class=\"card-body\">\r\n");
            out.write("											<p>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.categoryId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("											<h4 class=\"card-product__title\">\r\n");
            out.write("												<a\r\n");
            out.write("													href=\"ProductController?action=details&id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.productId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a>\r\n");
            out.write("											</h4>\r\n");
            out.write("											<p class=\"card-product__price\">$");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("										</div>\r\n");
            out.write("									</div>\r\n");
            out.write("								</div>\r\n");
            out.write("							");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
